apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-nginx
  # namespace: example-namespace
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
    # type: RollingUpdate
    # rollingUpdate:
    #   maxSurge: 10%
    #   maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: pythonappp
        image: vinaay/pythonapp:v7
        ports:
        - containerPort: 8002
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"