apiVersion: v1
kind: Pod
metadata:
  name: pythonapp
spec:
  containers:
  - name: pythonapp
    image: vinaay/pythonapp:v1
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
