apiVersion: v1
kind: Pod
metadata:
  name: pythonapp1
  labels:
    app: pythonapp1
spec:
  containers:
  - name: pythonapp1
    image: vinaay/pythonapp:v1
    ports:
    - containerPort: 8002
    readinessProbe:
      tcpSocket:
        port: 8002
      initialDelaySeconds: 15
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: 8002
      initialDelaySeconds: 15
      periodSeconds: 10
