apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-pending
  labels:
    app: pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: vinaay/pythonapp:v2
        ports:
        - containerPort: 8002
        resources:
         requests:
          cpu: "10"
          memory: "20Mi"