apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  player_initial_lives: "dmluYXkK"
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod1
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
  containers:
    - name: dotfile-test-container
      image: alpine
      command: ["sleep", "3600"]
      env:
        # Define the environment variable
        - name: PLAYER_INITIAL_LIVES # Notice that the case is different here
                                     # from the key name in the ConfigMap.
          valueFrom:
            secretKeyRef:
              name: dotfile-secret           # The ConfigMap this value comes from.
              key: player_initial_lives # The key to fetch.