apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: nginx
    command: ["sh", "-c", "echo Hello from BusyBox! >> data && sleep 200"]
    volumeMounts:
    - mountPath: /cache
      name: task-pv-storage
  volumes:
    - name: task-pv-storage
      hostPath:
        path: /tmp
        type: Directory